apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gke-ingress-config
  namespace: istio-system
spec:
  healthCheck:
    type: HTTP
    port: 15021
    requestPath: /healthz/ready