apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rabbitmq
  namespace: istio-system
spec:
  host: rabbitmq.rabbitmq.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
