kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "cert-manager-istio-csr.labels" . | indent 4 }}
  name: {{ include "cert-manager-istio-csr.name" . }}
  namespace: {{ .Values.app.certmanager.namespace }}
rules:
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificaterequests"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "delete"
  - "watch"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "create"
  - "update"
  - "watch"
  - "list"
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
